from F_taste_paziente.models.paziente import PazienteModel
from F_taste_paziente.models.consensi_utente import ConsensiUtenteModel
from F_taste_paziente.models.log_consensi import LOGConsensi
from F_taste_paziente.models.nutrizionista import NutrizionistaModel
from F_taste_paziente.models.richiesta_aggiunta_paziente import RichiestaAggiuntaPazienteModel
from F_taste_paziente.models.richiesta_revocata import RichiestaRevocataModel
from F_taste_paziente.models.informativa import InformativaBreveModel