from flaskr.models.paziente import PazienteModel
from flaskr.models.allergia_paziente import AllergiaPaziente
from flaskr.models.allergia import AllergiaModel
from flaskr.models.consensi_utente import ConsensiUtenteModel
from flaskr.models.intolleranza_paziente import IntolleranzaPaziente
from flaskr.models.intolleranza import IntolleranzaModel
from flaskr.models.log_consensi import LOGConsensi
from flaskr.models.nutrizionista import NutrizionistaModel
from flaskr.models.patologia_paziente import PatologiaPaziente
from flaskr.models.patologia import PatologiaModel
from flaskr.models.richiesta_aggiunta_paziente import RichiestaAggiuntaPazienteModel
from flaskr.models.richiesta_revocata import RichiestaRevocataModel